# Generated by Django 5.1.3 on 2025-05-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
